services:
  - type: web
    name: footprintx-backend
    env: node
    rootDir: FootprintX-main/backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: 2a61bb0a8ab262987ece42246cca2ad438c972b58ec19930599dc9dc4b43cefc
      - key: JWT_EXPIRATION
        value: 7d
      - key: FRONTEND_URL
        value: https://foot-print-x-frontend.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: footprintx-db
          property: connectionString
  
  - type: postgres
    name: footprintx-db
    plan: free
    ipAllowList: []
