services:
  - type: web
    name: footprintx-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    repo: https://github.com/BHOOMI764/FootPrintX-Project
    branch: main
    root: backend
    envVars:
      - key: JWT_SECRET
        value: YOUR_JWT_SECRET
      - key: JWT_EXPIRATION
        value: 1h
      - key: DATABASE_URL
        value: ""

databases:
  - name: footprintx-db
    engine: POSTGRES
    plan: starter
